#!/usr/bin/env node
require('reflect-metadata')
require('source-map-support/register')

const { Ignitor } = require('@adonisjs/core/build/standalone')

new Ignitor(__dirname).ace().handle(process.argv.splice(2))
